version: "3"
services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/work/
    links:
      - db
    tty: true

  db:
    image: mysql:5.7
    volumes:
      - db-store
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_USER: "ken"
      MYSQL_PASSWORD: "secret"
      MYSQL_DATABASE: "test"
    ports:
      - 13306:3306

volumes:
  db-store: